from enum import IntEnum, auto


class MonsterType(IntEnum):
    GOBLIN = auto()
    ORC = auto()
    DRAGON = auto()
    SKELETON = auto()
    ZOMBIE = auto()
    WOLF = auto()
    TROLL = auto()
    VAMPIRE = auto()
    GIANT_SPIDER = auto()
    ELEMENTAL = auto()
    LICH = auto()
    DARK_KNIGHT = auto()
    OGRE = auto()
    SLIME = auto()
    BANDIT = auto()
    WARLOCK = auto()
    GOLEM = auto()
    PHANTOM = auto()
    DEMON = auto()
    HYDRA = auto()
    PHOENIX = auto()
    GRIFFIN = auto()
    WYVERN = auto()
    TREANT = auto()
    MINOTAUR = auto()
    MANTICORE = auto()
    BANSHEE = auto()
    SIREN = auto()
    YETI = auto()
    KRAKEN = auto()
    SPECTER = auto()
    NAGA = auto()
