mage:
    # 1) Оценка угрозы (DPS) — приоритет убивать опасных врагов
    threat:
        use_accuracy: true # учитывать точность врага
        use_interval: true # учитывать скорость атак
        resist_modifier: 0.7 # если есть resistance к магии — DPS × 0.7
        weak_modifier: 1.3 # если есть weakness к магии — DPS × 1.3

    # 2) Весовые коэффициенты по тегам
    tag_weights:
        humanoid: 1.0
        dragon: 1.2
        elemental: 1.1
        magic: 1.0
        undead: 1.0
        beast: 0.9
        default: 1.0

    # 3) Учет ресурсов
    resource:
        consider_mana_regen: true # прикидывать манареген следующего хода

    # 4) Параметры утилит для каждого скилла
    skills:
        "Fireball":
            enabled: true
            cd_weight: 1.0

        "Magic Barrier":
            enabled: true
            hp_pct: 0.5 # применять, если HP < 50%
            shield_pct: 0.25 # щит = 25% max_HP
            cd_weight: 1.0

        "Chain Lightning":
            enabled: true
            min_enemies: 1 # минимум целей
            cd_weight: 1.0

        "Mana Drain":
            enabled: true
            mana_threshold: 0.5 # применять, если осталось маны < 50%
            cd_weight: 1.0

        "Meteor":
            enabled: true
            min_enemies: 1 # минимум целей
            cd_weight: 1.0

        "Time Warp":
            enabled: true
            utility_weight: 0.5 # лёгкий utility
            cd_weight: 1.0
