# =======================================================================
#  BATTLE RULES — мастер‑конфиг боевой системы
# =======================================================================

# -----------------------------------------------------------------------
# 1. ПОРЯДОК ХОДОВ
# -----------------------------------------------------------------------
turn_order:
    algorithm: "agility_priority" # ► варианты: agility_priority | speed | random
    random_weight: 0.10 # ► 0 = полный детерминизм, 1 = полный рандом

# -----------------------------------------------------------------------
# 2. ПРАВИЛА РАСЧЁТА УРОНА
# -----------------------------------------------------------------------
damage_rules:
    # --- вклад характеристик ---
    coeffs:
        phys: 1.0 # множитель силы (strength)
        mag: 1.0 # множитель интеллекта (intelligence)

    # --- рост с уровнем ---
    level_coeff:
        player: 0.05 # +5 % урона за уровень
        monster: 0.03 # +3 % урона за уровень

    # --- случайный разброс ---
    variance:
        min: 0.90 # −10 %
        max: 1.10 # +10 %

    # --- критические удары ---
    crit:
        multiplier: # множители по типу крита (см. CritType)
            normal: 1.5 # x1.5 (по умолчанию)
            heavy: 2.0 # x2.0 (особые навыки)

    # --- минимум после всех вычетов ---
    min_damage: 1

# -----------------------------------------------------------------------
# 3. ШАНС ПОПАДАНИЯ / УКЛОНЕНИЯ
# -----------------------------------------------------------------------
hit_chance:
    logistic: # σ(x) = 1 / (1 + e^(-(Δ − x0)/k))
        x0: 0 # Δ Agility = 0 → 50 %
        k: 3.0 # кривая положе
    scale: 2 # Δ Agility (сглаживание)
    clamp:
        min: 0.35
        max: 0.95

dodge:
    base_chance_attr: "dodge_chance"

# -----------------------------------------------------------------------
# 4. ЗАЩИТА
# -----------------------------------------------------------------------
defense:
    reduction_per_point: 1 # 1 defense = −1 урона
    min_damage: 1 # нижний порог после вычета брони

# -----------------------------------------------------------------------
# 5. ЭЛЕМЕНТЫ
# -----------------------------------------------------------------------
elements:
    resist_multiplier: 0.5 # ×0.5, если цель имеет сопротивление
    weak_multiplier: 1.5 # ×1.5, если цель уязвима

# -----------------------------------------------------------------------
# 6. КУЛДАУНЫ
# -----------------------------------------------------------------------
skill_cooldown:
    decrease_phase: "end_of_user_turn" # варианты: start_of_turn | end_of_turn | end_of_user_turn

# -----------------------------------------------------------------------
# 7. ТРИГГЕРЫ НАВЫКОВ
# -----------------------------------------------------------------------
skill_triggers:
    always: { event: "on_turn_start" }
    if_enemy_low_hp: { event: "on_target_hp_below", threshold: 0.30 }
    on_low_hp: { event: "on_self_hp_below", threshold: 0.30 }
    on_fatal_hit: { event: "on_incoming_damage", condition: "would_be_fatal" }
    if_first: { event: "on_attack_start", condition: "is_first_attack" }

# -----------------------------------------------------------------------
# 8. СТАТУС‑ЭФФЕКТЫ
# -----------------------------------------------------------------------
status_effects:
    stun:
        prevents_action: true

    provoke:
        force_target: "self"

    poison:
        periodic_damage: 0.05 # 5 % от max HP за ход
        duration_decrement: "end_of_turn"

    burn:
        periodic_damage: 0.10
        duration_decrement: "end_of_turn"

    reduce_damage:
        damage_multiplier: 0.85 # входящий урон ×0.85

    increased_evasion:
        evasion_bonus: 0.20 # +20 % к dodge‑chance

    magic_shield:
        absorb_amount: 0.60 # поглощает 60 % max HP суммарно

    steal_intelligence: # переопределяем как манадрейн
        mana_recover: 0.40 # восстанавливает 40 % от max_mana атакующего
        duration_decrement: "none" # срабатывает сразу, не периодически

    extra_turn:
        grants_turn: true

# -----------------------------------------------------------------------
# 9. ПРАВИЛА БАФФОВ / ДЕБАФФОВ
# -----------------------------------------------------------------------
buff_rules:
    stacking: "refresh" # refresh | independent | stack
    max_stacks: 1

# -----------------------------------------------------------------------
# 10. AOE — ВЫБОР ЦЕЛЕЙ
# -----------------------------------------------------------------------
aoe_targets:
    all_enemies: { type: "all", side: "enemy" }
    team: { type: "all", side: "ally" }
    two_random_enemies: { type: "random", count: 2, side: "enemy" }

# -----------------------------------------------------------------------
# 11. ПОРЯДОК РАЗРЕШЕНИЯ ЭФФЕКТОВ (внутри хода)
# -----------------------------------------------------------------------
effect_resolution:
    - "triggered_passives"
    - "status_effects_start"
    - "skill_activation"
    - "damage_application"
    - "status_effects_end"

# -----------------------------------------------------------------------
# 12. АУРЫ / СИНЕРГИИ ОТРЯДА
# -----------------------------------------------------------------------
auras:
    synergy_rules:
        two_mages:
            effect: "bonus_magic_damage"
            value: 0.10 # +10 % маг. урона всему отряду
