# src/config/growth.yaml

# -------------------------------------------------------------------
# 1. Прирост характеристик за уровень
# -------------------------------------------------------------------
WARRIOR:
    health: 12 # +12 HP за уровень
    strength: 2 # +2 STR
    agility: 1 # +1 AGI
    intelligence: 0 # +0 INT
    defense: 1 # +1 DEF
    accuracy: 0.005 # +0.5% точности
    crit_chance: 0.002 # +0.2% крита
    dodge_chance: 0.002 # +0.2% уклонения

MAGE:
    health: 6 # +6 HP
    strength: 0
    agility: 1
    intelligence: 3 # +3 INT
    defense: 0
    accuracy: 0.005 # +0.5% точности
    crit_chance: 0.003 # +0.3% крита
    dodge_chance: 0.003 # +0.3% уклонения
    mana: 10 # +10 маны
    mana_regen: 0.5 # +0.5 маны/ход

ROGUE:
    health: 8 # +8 HP
    strength: 1 # +1 STR
    agility: 3 # +3 AGI
    intelligence: 1 # +1 INT
    defense: 0.5 # +0.5 DEF
    accuracy: 0.007 # +0.7% точности
    crit_chance: 0.005 # +0.5% крита
    dodge_chance: 0.005 # +0.5% уклонения

# -------------------------------------------------------------------
# 2. Кривая опыта
# -------------------------------------------------------------------
exp_curve:
    base: 100
    exponent: 1.5

# -------------------------------------------------------------------
# 3. Награды за победы по тиру
# -------------------------------------------------------------------
xp_rewards:
    tier1: 20000 # Новобранцы
    tier2: 50 # Ветераны
    tier3: 100 # Легенды
    tier4: 200 # Владыки
